- hosts: windows
  vars_files:
    - "../network_drives.yml"

  tasks:
    - name: Ensure network drives are mapped
      community.windows.win_mapped_drive:
        letter: "{{ item.letter }}"
        path: "{{ item.path }}"
        username: "{{ item.username }}"
        password: "{{ item.password }}"
        state: present
      loop: "{{ network_drives }}"
      #become: true
      #become_method: runas
      #become_user: "{{ ansible_user }}"


    # Optional: Verify drive mapping
    - name: Verify drive mapping
      ansible.windows.win_command: "net use"
      register: drive_mapping_result
      changed_when: false

    - name: Display drive mapping
      debug:
        var: drive_mapping_result.stdout_lines