---
- name: Install Miniconda3 using Chocolatey and set up Python environment on Windows
  hosts: windows
  tasks:

    - name: Ensure Chocolatey is installed
      win_chocolatey:
        name: chocolatey
        state: present

    - name: Install Miniconda3 using Chocolatey
      win_chocolatey:
        name: miniconda3
        state: present

    - name: Add Miniconda to PATH
      win_environment:
        name: Path
        value: 'C:\tools\miniconda3;C:\tools\miniconda3\Scripts;C:\tools\miniconda3\tools;C:\tools\miniconda3\Library\bin'
        state: present
        level: user # or machine

    - name: Create conda environment
      win_command: 'C:\tools\miniconda3\Scripts\conda.exe create -n suite2p python=3.8 -y'
      args:
        creates: C:\tools\miniconda3\envs\suite2p

    - name: Install packages using pip in the conda environment
      win_command: 'C:\tools\miniconda3\Scripts\conda.exe run -n suite2p pip install suite2p'
