#TODO: implement this settings for setting up oh my posh
  #TODO: add starship design
  #TODO: add meslo nerd font?
  0. winget install JanDeDobbeleer.OhMyPosh -s winget
  1. `notepad $PROFILE`
  #add to profile
  2. set theme to powerlevel10k rainbow `oh-my-posh init pwsh --config "$env:POSH_THEMES_PATH/powerlevel10k_rainbow.omp.json" | Invoke-Expression`
  3. Add showing virtual environment to theme: 
    1. open notepad $env:POSH_THEMES_PATH/powerlevel10k_rainbow.omp.json  
    2. Add following lines to blocks: alignment left : segments (as shown in the file `Windows/posh/theme/powerlevel10k_rainbow_env.omp.json`
  ```json
          {
          "type": "python",
          "trailing_diamond": "\ue0b4",
          "leading_diamond": "<transparent,background>\ue0b0</>",
          "style": "diamond",
          "powerline_symbol": "\uE0B0",
          "foreground": "#100e23",
          "background": "#906cff",
          "template": " \uE235 {{ .Full }} {{ if .Venv }}{{ .Venv }}{{ end }}",
          "properties": {
              "fetch_virtual_env": true,
              "display_mode": "environment",
              "home_enabled": true
          }
  ```
  4. relode profile by running `. $PROFILE`
  # or other theme that can be found here Get-PoshThemes, the theme name neets to be pu instead of powerlevel10k_rainbow

#TODO: implement this settings for setting up cygwin

Install-Module -Name PSReadLine -Scope CurrentUser -Force 
Set-ExecutionPolicy RemoteSigned
