- name: Setup Windows Terminal and Oh My Posh
  hosts: windows
  tasks:
    - name: Install Oh My Posh using Winget
      win_shell: |
        winget install --id JanDeDobbeleer.OhMyPosh -e --source winget

    - name: Clone the Git repository to the Downloads folder
      git:
        repo: https://github.com/Ch3fUlrich/AutoOS.git
        dest: C:\Users\{{ lookup('env', 'USERPROFILE') }}\Downloads
        clone: yes
        update: yes
        
    #TODO: save fonts in repository and download from there
    - name: Install Meslo Nerd Font
      win_shell: |
        Invoke-WebRequest -Uri "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/Meslo.zip" -OutFile "C:\Temp\Meslo.zip"
        Expand-Archive -Path "C:\Temp\Meslo.zip" -DestinationPath "C:\Windows\Fonts"
        Remove-Item -Path "C:\Temp\Meslo.zip"

    - name: Ensure PowerShell profile exists
      win_file:
        path: "{{ lookup('env', 'USERPROFILE') }}\\Documents\\WindowsPowerShell\\Microsoft.PowerShell_profile.ps1"
        state: touch

    - name: Add Oh My Posh initialization to $PROFILE
      win_lineinfile:
        path: "{{ lookup('env', 'USERPROFILE') }}\\Documents\\WindowsPowerShell\\Microsoft.PowerShell_profile.ps1"
        line: 'oh-my-posh init pwsh --config "$env:POSH_THEMES_PATH/powerlevel10k_rainbow.omp.json" | Invoke-Expression'
        create: yes


    - name: Copy custom theme to Oh My Posh themes folder
      copy:
        src: C:\Users\{{ lookup('env', 'USERPROFILE') }}\Downloads\AutoOS\Windows\Terminal\oh-my-posh\theme\powerlevel10k_rainbow_env.omp.json
        dest: C:\Users\{{ lookup('env', 'USERPROFILE') }}\Documents\WindowsPowerShell\powerlevel10k_rainbow_env.omp.json
        force: yes
        backup: yes

    - name: Install PSReadLine module
      win_shell: |
        Install-Module -Name PSReadLine -Scope CurrentUser -Force

    - name: Set execution policy to RemoteSigned
      win_shell: |
        Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Force

    - name: Reload PowerShell profile
      win_shell: |
        . $PROFILE
