all:
  vars:
    # Windows credentials
    windows_ip: 131.152.9.67
    windows_user: 'DonatoLab'
    windows_password: 'asdf'

    # Placeholder for drives
    unibas_mail: 'bla.bla@unibas.ch'
    unibas_password: 'good_password'
    toucan_drive_username: blabl0000

  hosts:
    windows:
      ansible_host: '{{ windows_ip }}'
      ansible_user: '{{ windows_user }}'
      ansible_password: '{{ windows_password }}'
      ansible_connection: ssh
      ansible_shell_type: cmd

