---
- name: Main playbook
  hosts: windows
  vars_files:
    - software_links.yml
    - network_drives.yml


- import_playbook: playbooks/chocolatey_software.yml
- import_playbook: playbooks/add_drives.yml
- import_playbook: playbooks/python_miniconda_suite2p.yml
- import_playbook: playbooks/down_install_software.yml
- import_playbook: playbooks/terminal_setup.yml