---
- name: Main playbook
  hosts: windows
  vars_files:
    - software_links.yml
    - network_drives.yml

  tasks:

    - name: run chocolatey_software playbook
      import_playbook: playbooks/chocolatey_software.yml

    - name: add remote drives to windows
      import_playbook: playbooks/add_drives.yml

    - name: create suite2p environment in conda
      import_playbook: playbooks/python_miniconda_suite2p.yml

    - name: install realtime_sync
      import_playbook: playbooks/down_install_software.yml

