---
- name: Install software on Windows 11
  hosts: localhost
  tasks:
    - name: Ensure Chocolatey is installed
      win_get_url:
        url: https://chocolatey.org/install.ps1
        dest: C:\chocolatey-install.ps1
      register: choco_install

    - name: Run Chocolatey installation script
      win_shell: powershell -NoProfile -InputFormat None -ExecutionPolicy Bypass -File C:\chocolatey-install.ps1
      when: choco_install.changed

    - name: Install software via Chocolatey
      win_chocolatey:
        name: "{{ item }}"
        state: present
      loop:
        ## Usefull Tools
        - 7zip
        - powertoys
        - treesizefree

        ## music and video
        - spotify
        - vlc
        
        ## browsers
        - firefox
        - googlechrome

        ## file sync and cloud
        - switchdrive
        - owncloud-client
        
        ## remote controll
        - teamviewer
        - parsec

        ## vpn
        - globalprotect
        - wireguard

        ## communication
        - slack

        ## notes
        - zotero
        - obsidian
        - notepadplusplus

        ## code
        # python
        - vscode
        # matlab
        - mcr-r2023b

    - name: Ensure pip is installed for Python
      win_command: "python -m ensurepip"
      when: python_installed.changed

    - name: Clean up Chocolatey installation script
      win_file:
        path: C:\chocolatey-install.ps1
        state: absent        