- name: Install software on Windows 11
  hosts: windows
  vars_files:
      - "{{ lookup('env', 'PROJECT_ROOT') }}/credentials.yml"....

  tasks:

    - name: Ensure Chocolatey is installed
      win_get_url:
        url: https://chocolatey.org/install.ps1
        dest: C:\chocolatey-install.ps1
      register: choco_install

    - name: Run Chocolatey installation script
      win_shell: powershell -NoProfile -ExecutionPolicy Bypass -File C:\chocolatey-install.ps1
      when: choco_install.changed

    - name: Install software via Chocolatey
      win_chocolatey:
        name: "{{ item }}"
        state: present
      loop:
        # Useful Tools
        - 7zip
        - powertoys
        - treesizefree

        # Music and Video
        - spotify
        - vlc
        
        # Browsers
        - firefox
        - googlechrome

        # File Sync and Cloud
        - switchdrive
        - owncloud-client
        
        # Remote Control
        - teamviewer
        - parsec

        # VPN
        - wireguard

        # Communication
        - slack

        # Notes
        - zotero
        - obsidian
        - notepadplusplus

        # Code
        - vscode
        # Uncomment the following lines if you want to install Python and MATLAB
        # - python
        # - mcr-r2023b

    - name: Ensure pip is installed for Python
      win_command: "python -m ensurepip"
      register: python_installed
      ignore_errors: true  # Added to prevent failure if Python is not installed

    - name: Clean up Chocolatey installation script
      win_file:
        path: C:\chocolatey-install.ps1
        state: absent