- name: Install additional software
  hosts: windows
  vars_files:
    - "../software_links.yml"

  tasks:
    - name: Create installer directory
      win_file:
        path: "{{ playbook_dir }}\\..\\installs"
        state: directory

    - name: Download installers
      win_get_url:
        url: "{{ item.url }}"
        dest: "{{ playbook_dir }}\\..\\installs\\{{ item.filename }}"
      loop: "{{ software_list }}"
      register: download_status

    - name: Install software via MSI
      win_package:
        path: "{{ playbook_dir }}\\..\\installs\\{{ item.filename }}"
        state: present
        arguments: "{{ item.silent_args }}"
      loop: "{{ software_list }}"
      when: item.install_method == 'msi'
      register: msi_install_status

    - name: Install software via EXE
      win_command: "Start-Process -FilePath '{{ playbook_dir }}\\..\\installs\\{{ item.filename }}' -ArgumentList '{{ item.silent_args }}' -Wait"
      args:
        chdir: "{{ playbook_dir }}\\..\\installs"
      loop: "{{ software_list }}"
      when: item.install_method == 'exe'
      register: exe_install_status

    - name: Display installation results
      debug:
        msg: 
          - "Downloaded: {{ download_status.results | selectattr('changed') | list | length }} items"
          - "MSI Installed: {{ msi_install_status.results | selectattr('changed') | list | length }} items"
          - "EXE Installed: {{ exe_install_status.results | selectattr('changed') | list | length }} items"