- name: Test Ansible Connectivity to Windows
  hosts: windows
  tasks:
    - name: Check Windows uptime
      ansible.windows.win_command:
        cmd: systeminfo | find "System Boot Time"

    - name: Create a test file
      ansible.windows.win_file:
        path: C:\TestFile.txt
        state: touch
